services:
  - type: web
    name: smart-process-cron
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BITRIX_WEBHOOK
        value: https://cab.bitrix24.ru/rest/1/s3a6coos9gt5lsw9/
